### ISSUE TITLE
October topics

### ISSUE THREAD

**Issue by justinmoon** [austinbitdevs/austinbitdevs.com#11]
https://blog.lopp.net/was-satoshi-a-greedy-miner/

**Comment by justinmoon** [comment]
Tor-style network on top of lightning https://github.com/Indra-Labs/indra

**Comment by benthecarman** [comment]
https://assets-global.website-files.com/614e11536f66309636c98688/63208342664438223226c3de_NYDIG%20-%20Developers%20of%20Bitcoin%202022.pdf

**Comment by benthecarman** [comment]
https://twitter.com/sphinx_chat/status/1571974701098074112?s=20&t=xO_L4nODsb8gW9nZ4XAZ1Q

**Comment by benthecarman** [comment]
https://github.com/lnproxy/lnproxy

**Comment by benthecarman** [comment]
https://blog.bitmex.com/erroneous-findings-in-merkle-trees-optimized-for-stateless-clients-in-bitcoin/

**Comment by bucko13** [comment]
New transaction policies (nVersion=3) for contracting protocols
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-September/020937.html

**Comment by benthecarman** [comment]
> New transaction policies (nVersion=3) for contracting protocols [lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-September/020937.html](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-September/020937.html)

oh god

**Comment by benthecarman** [comment]
https://research.chaincode.com/2022/09/16/introduction/

**Comment by bucko13** [comment]
Report in Nature on distribution of mining 
https://www.nature.com/articles/s41598-022-14987-0

**Comment by benthecarman** [comment]
https://gist.github.com/Kixunil/94f829ff2371a4f1224c88bc587addf7

**Comment by benthecarman** [comment]
https://lightning.engineering/posts/2022-9-28-taro-launch/

**Comment by benthecarman** [comment]
https://supertestnet.github.io/bitcoin-lottery-contract/mainnet.html

**Comment by benthecarman** [comment]
https://github.com/L2-Technology/sensei/pull/121

**Comment by cryptoquick** [comment]
P2C fields in PSBTs BIP-372 was recently added https://github.com/bitcoin/bips/pull/1293

**Comment by kanzure** [comment]
https://www.blockchaincommons.com/quarterlies/Q3-2022/

**Comment by benthecarman** [comment]
https://github.com/ACINQ/eclair/pull/2435

**Comment by benthecarman** [comment]
https://mempool.space/tx/7393096d97bfee8660f4100ffd61874d62f9a65de9fb6acf740c4c386990ef73

**Comment by benthecarman** [comment]
https://twitter.com/brqgoo/status/1579216353780957185?s=20&t=46GSLdU9EdTx611ujT54UQ

**Comment by benthecarman** [comment]
https://github.com/lightningnetwork/lnd/issues/7002

**Comment by benthecarman** [comment]
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-October/020980.html

**Comment by bucko13** [comment]
Instant chain state verification with zksnarks and utreexo https://github.com/lucidLuckylee/zerosync

**Comment by benthecarman** [comment]
https://github.com/bitcoin/bitcoin/pull/26348

**Comment by bucko13** [comment]
BIP Bounty project launch (could just be in the announcements section) https://twitter.com/notasithlord/status/1580942321108910080?s=46&t=AmUC5uHhY1vk6-w6a_RJwg
