### ISSUE TITLE
March Topics

### ISSUE THREAD

**Issue by benthecarman** [austinbitdevs/austinbitdevs.com#17]

**Comment by justinmoon** [comment]
https://www.zestprotocol.com/

**Comment by justinmoon** [comment]
https://github.com/bits-wallet/specs

**Comment by benthecarman** [comment]
https://bitcoinmagazine.com/technical/bitcoin-core-maintainer-marco-falke-to-step-down

**Comment by justinmoon** [comment]
https://eprint.iacr.org/2022/1295.pdf

**Comment by benthecarman** [comment]
https://github.com/lightningnetwork/lnd/issues/7301

**Comment by justinmoon** [comment]
https://github.com/fedimint/fedimint/pull/1621

**Comment by benthecarman** [comment]
https://twitter.com/blksresearch/status/1631020006883377154?s=20

**Comment by justinmoon** [comment]
https://twitter.com/RollkitDev/status/1632438374513676288?s=20

**Comment by justinmoon** [comment]
https://twitter.com/ercwl/status/1633166395922939913

**Comment by benthecarman** [comment]
https://github.com/bitcoin-core/secp256k1/blob/master/CHANGELOG.md#030---2023-03-08

**Comment by justinmoon** [comment]
https://github.com/rootzoll/raspiblitz/issues/3706

**Comment by justinmoon** [comment]
A guy attending wants to show off some bitcoin core gui improvements … https://github.com/bitcoin-core/gui-qml/tree/main/src

**Comment by justinmoon** [comment]
https://github.com/bitcoin/bips/pull/1425

**Comment by bennyhodl** [comment]
https://twitter.com/lightningdevkit/status/1635392924463804417?s=20

**Comment by justinmoon** [comment]
https://www.theblock.co/post/219992/blockchain-startup-tari-labs-wins-restraining-order-against-lightning-labs-over-taro-protocol

**Comment by bennyhodl** [comment]
https://github.com/bennyhodl/baywallet

**Comment by justinmoon** [comment]
https://twitter.com/_WolfNYC/status/1636352620049694728

**Comment by bennyhodl** [comment]
https://github.com/bennyhodl/baywallet
^ the most important project in ₿itcoin rn

**Comment by justinmoon** [comment]
https://github.com/bitcoin-core/secp256k1/releases/tag/v0.3.0

**Comment by justinmoon** [comment]
https://github.com/nostr-protocol/nips/pull/224

**Comment by justinmoon** [comment]
assumeutxo progress:
- https://github.com/bitcoin/bitcoin/pull/25740
- https://github.com/bitcoin/bitcoin/projects/11

**Comment by justinmoon** [comment]
Fedimint
- https://github.com/fedimint/fedimint/pull/1855
- https://github.com/fedimint/fedimint/pull/1907
- https://github.com/fedimint/fedimint/pull/1564
- https://github.com/fedimint/fedimint/pull/1363
- https://github.com/fedimint/fedimint/pull/1735

**Comment by justinmoon** [comment]
utreexo testing on testnet / signet https://bitcoinops.org/en/newsletters/2023/03/15/#service-bit-for-utreexo

**Comment by justinmoon** [comment]
https://unchained.com/blog/multisig-security-ledger/
