### ISSUE TITLE
April topics

### ISSUE THREAD

**Issue by benthecarman** [austinbitdevs/austinbitdevs.com#18]

**Comment by benthecarman** [comment]
https://github.com/bitcoin/bitcoin/pull/27050

**Comment by benthecarman** [comment]
https://twitter.com/jamesob/status/1639019107432513537

**Comment by benthecarman** [comment]
https://twitter.com/realtbast/status/1640606307924291585

**Comment by benthecarman** [comment]
https://twitter.com/1440000bytes/status/1640269691569737728

**Comment by justinmoon** [comment]
https://twitter.com/realtbast/status/1640606307924291585?s=20

**Comment by benthecarman** [comment]
https://b10c.me/observations/06-linkinglion/

**Comment by justinmoon** [comment]
https://bitcoinmagazine.com/technical/zerosync-reduces-bitcoin-node-validation

**Comment by justinmoon** [comment]
https://twitter.com/Erik17192799/status/1640831466085990400?s=20

**Comment by benthecarman** [comment]
https://medium.com/vinteum-org/introducing-floresta-an-utreexo-powered-electrum-server-implementation-60feba8e179d

**Comment by justinmoon** [comment]
https://twitter.com/BobMcElrath/status/1641106981816606723?s=20

**Comment by justinmoon** [comment]
This could be kind of a fun discussion topic https://twitter.com/super_testnet/status/1643420462498603008?s=20 cc @supertestnet

**Comment by bucko13** [comment]
Plebfi event in Miami

https://twitter.com/PlebFi/status/1643348809483980800?s=20

**Comment by justinmoon** [comment]
https://lists.linuxfoundation.org/pipermail/lightning-dev/2023-March/003886.html

**Comment by justinmoon** [comment]
https://github.com/civkit/paper/blob/main/civ_kit_paper.pdf
