### ISSUE TITLE
May topics

### ISSUE THREAD

**Issue by justinmoon** [austinbitdevs/austinbitdevs.com#19]

**Comment by justinmoon** [comment]
https://gist.github.com/RobinLinus/d036511015caea5a28514259a1bab119

**Comment by justinmoon** [comment]
https://github.com/MostroP2P/mostro

**Comment by justinmoon** [comment]
https://github.com/nbd-wtf/soma

**Comment by bucko13** [comment]
Spiral hiring bitcoin wizards https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-April/021549.html

**Comment by benthecarman** [comment]
https://github.com/bitcoin/bitcoin/pull/25325

**Comment by benthecarman** [comment]
https://github.com/supertestnet/breaker-of-jpegs

**Comment by benthecarman** [comment]
https://twitter.com/binance/status/1655419624962527233?s=20

**Comment by bucko13** [comment]
Ledger vulnerability https://twitter.com/darosior/status/1656675643546042371?s=20

**Comment by benthecarman** [comment]
https://github.com/bitcoin/bitcoin/issues/27623

**Comment by bucko13** [comment]
BitResolve for FOSS dispute resolution. 

https://github.com/BitResolve/Bounty-Adjudication-System

**Comment by benthecarman** [comment]
https://github.com/bitcoin/bitcoin/issues/27677
