### ISSUE TITLE
June Topics

### ISSUE THREAD

**Issue by benthecarman** [austinbitdevs/austinbitdevs.com#20]

**Comment by benthecarman** [comment]
https://nitter.at/mempool/status/1659619347910803466?ref=nobsbitcoin.com

**Comment by benthecarman** [comment]
https://github.com/ffaex/altpay

**Comment by justinmoon** [comment]
https://www.arkpill.me/

**Comment by benthecarman** [comment]
https://blog.bitmex.com/lightning-payments-when-are-they-too-small-to-secure/

**Comment by benthecarman** [comment]
https://block21m.substack.com/p/most-bitcoin-inscriptions-belong-d6d

**Comment by bennyhodl** [comment]
https://github.com/bennyhodl/baywallet

**Comment by benthecarman** [comment]
https://twitter.com/DarkDotFail/status/1664324309689548827

**Comment by kanzure** [comment]
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-June/021734.html

**Comment by benthecarman** [comment]
https://eprint.iacr.org/2023/841

**Comment by benthecarman** [comment]
https://github.com/bitcoin/bitcoin/pull/27854

**Comment by kanzure** [comment]
https://blog.succinct.xyz/blog/btc-warp
