### ISSUE TITLE
Add Apple Touch Icon for Bookmarking on IPhones

### ISSUE THREAD

**Issue by MARQUEZ93** [austinbitdevs/austinbitdevs.com#21]
- Add `<link rel="apple-touch-icon" href="/apple-touch-icon.png" type="image/png" />` to [./_includes/head.html](https://github.com/austinbitdevs/austinbitdevs.com/blob/master/_includes/head.html)
- Then create a 180*180 png titled `apple-touch-icon.png` in the root directory from the [./favicon.ico ](https://github.com/austinbitdevs/austinbitdevs.com/blob/master/favicon.ico)

**Comment by benthecarman** [comment]
Think I implemented this, let me know if it works

**Comment by MARQUEZ93** [comment]
it works!
