### ISSUE TITLE
August ‘23 Topics

### ISSUE THREAD

**Issue by bucko13** [austinbitdevs/austinbitdevs.com#24]

**Comment by bucko13** [comment]
Lightning use case
https://blog.bitfinex.com/education/is-lightning-scaling-bitcoin-in-a-way-nobody-predicted/

**Comment by benthecarman** [comment]
https://github.com/ElementsProject/lightning/pull/6253

**Comment by benthecarman** [comment]
https://github.com/bitcoin/bitcoin/pull/28132

**Comment by benthecarman** [comment]
https://github.com/bitcoin/bitcoin/pull/28130

**Comment by bucko13** [comment]
utreexo implementation floresta: https://github.com/Davidson-Souza/Floresta

**Comment by benthecarman** [comment]
https://github.com/bitcoin/bitcoin/pull/27877

**Comment by benthecarman** [comment]
https://github.com/mit-dci/rustreexo/tree/v0.1.0

**Comment by kanzure** [comment]
https://blog.liquid.net/expanding-transparency-the-liquid-networks-functionary-code-is-now-open-source/
