### ISSUE TITLE
September topics

### ISSUE THREAD

**Issue by benthecarman** [austinbitdevs/austinbitdevs.com#25]

**Comment by benthecarman** [comment]
https://twitter.com/n1ckler/status/1693650163774963946?s=20

**Comment by bucko13** [comment]
Lightning DOS
https://morehouse.github.io/lightning/fake-channel-dos/

**Comment by benthecarman** [comment]
https://morehouse.github.io/lightning/fake-channel-dos/

**Comment by kanzure** [comment]
bitcoin script symbolic execution (a script debugger, or a free coin collector/solver....) https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-August/021922.html and https://github.com/dgpv/bsst

**Comment by benthecarman** [comment]
https://lists.linuxfoundation.org/pipermail/lightning-dev/2023-September/004088.html

**Comment by bucko13** [comment]
Instant light client sync with zero sync 

https://x.com/roasbeef/status/1700598667546419552?s=46

**Comment by bucko13** [comment]
Mk4 chip hacked


http://blog.coinkite.com/donjon-faults-2023/

**Comment by benthecarman** [comment]
https://lists.linuxfoundation.org/pipermail/lightning-dev/2023-September/004092.html

**Comment by benthecarman** [comment]
https://github.com/supertestnet/utxo-dealership

**Comment by bucko13** [comment]
Combined CTV + APO proposal: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-August/021907.html
