### ISSUE TITLE
October topics

### ISSUE THREAD

**Issue by benthecarman** [austinbitdevs/austinbitdevs.com#26]

**Comment by benthecarman** [comment]
https://b10c.me/observations/07-invalid-block-809478/

**Comment by benthecarman** [comment]
https://github.com/bitcoin/bitcoin/pull/28550

**Comment by kanzure** [comment]
https://github.com/bitcointranscripts/bitcointranscripts/pull/276

**Comment by benthecarman** [comment]
https://blog.mutinywallet.com/fixing-payment-reliability/

**Comment by benthecarman** [comment]
https://github.com/bitcoin/bitcoin/pull/27596

**Comment by benthecarman** [comment]
https://github.com/lightningnetwork/lnd/releases/tag/v0.17.0-beta

**Comment by benthecarman** [comment]
https://github.com/lightningnetwork/lnd/issues/7961

**Comment by benthecarman** [comment]
https://twitter.com/rot13maxi/status/1709011253350334887

**Comment by benthecarman** [comment]
https://github.com/lightningdevkit/rust-lightning/releases/tag/v0.0.117

**Comment by benthecarman** [comment]
https://t.co/Itf9UHos0C

**Comment by benthecarman** [comment]
https://ishaana.com/blog/wallet_fingerprinting/

**Comment by benthecarman** [comment]
https://x.com/m1sterc001guy/status/1712545382226645329?s=20

**Comment by kanzure** [comment]
https://twitter.com/peterktodd/status/1712738205160632347

**Comment by bennyhodl** [comment]
https://GitHub.coo/bennyhodl/baywallet

**Comment by bennyhodl** [comment]
mononaut adds two 31 bit unsigned integers in a bitvm circuit https://x.com/mononautical/status/1713291840638599206?s=46

**Comment by benthecarman** [comment]
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-October/021997.html

**Comment by benthecarman** [comment]
https://gitlab.com/-/snippets/3611229

**Comment by benthecarman** [comment]
https://lists.linuxfoundation.org/pipermail/lightning-dev/2023-October/004122.html

**Comment by kanzure** [comment]
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-October/022030.html
