### ISSUE TITLE
January '24 Topics

### ISSUE THREAD

**Issue by bucko13** [austinbitdevs/austinbitdevs.com#29]

**Comment by bucko13** [comment]
sCrypt: https://xiaohuiliu.medium.com/introduce-scrypt-a-layer-1-smart-contract-framework-for-btc-b8b39c125c1a

**Comment by bucko13** [comment]
Fedimint 0.2.1 federate all the things:

https://github.com/fedimint/fedimint/releases/tag/v0.2.1

**Comment by bucko13** [comment]
Bitcoin Clique for offchain payments

https://eprint.iacr.org/2024/025

**Comment by bucko13** [comment]
LNHANCE
https://delvingbitcoin.org/t/lnhance-bips-and-implementation/376

**Comment by bucko13** [comment]
CLN vulnerability

**Comment by bucko13** [comment]
64 bit arithmetic proposal
https://delvingbitcoin.org/t/64-bit-arithmetic-soft-fork/397

**Comment by bucko13** [comment]
Cluster mempool summary
https://delvingbitcoin.org/t/an-overview-of-the-cluster-mempool-proposal/393/

**Comment by bucko13** [comment]
Mercury Layer
https://mercurylayer.com/

**Comment by bucko13** [comment]
Rethinking lightning:
https://stacker.news/items/379225?ref=rogerprice.me

**Comment by bucko13** [comment]
Fedimint support in Mutiny:
https://primal.net/e/note13y66pezucap8tjjf80q2mzmc387u6e3jujzk97736lmck972m8ns00s3j7

**Comment by bucko13** [comment]
Replit thinking about using bitcoin and lightning https://twitter.com/amasad/status/1738003006048923697

**Comment by bucko13** [comment]
Peter Todd critique of v3 transactions and anchors in general: https://petertodd.org/2023/v3-transactions-review

Optech summary of discussion: https://bitcoinops.org/en/newsletters/2024/01/10/

**Comment by bucko13** [comment]
LN-Symmetry project update: https://delvingbitcoin.org/t/ln-symmetry-project-recap/359

**Comment by justinmoon** [comment]
Posted all these to the list https://austinbitdevs.com/2024-01-18-socratic-seminar-48
