### ISSUE TITLE
February '24 Topics

### ISSUE THREAD

**Issue by justinmoon** [austinbitdevs/austinbitdevs.com#30]

**Comment by benthecarman** [comment]
https://github.com/bitcoin/bitcoin/pull/29291

**Comment by justinmoon** [comment]
https://twitter.com/citrea_xyz/status/1754883284893356368

**Comment by bucko13** [comment]
summer of bitcoin: https://twitter.com/summerofbitcoin/status/1753414874045329505?s=20

**Comment by benthecarman** [comment]
https://github.com/bitcoin/bitcoin/pull/28948

**Comment by kanzure** [comment]
https://twitter.com/kanzure/status/1756055826723217659

**Comment by justinmoon** [comment]
https://primal.net/e/note1z6cwn6v5wp4c6yvzq2d8jqf8nxzrl69c2nl0f03nu434pvfqu9ls5lrp4d

**Comment by bucko13** [comment]
v3 transaction policy for anti-pinning

https://github.com/bitcoin/bitcoin/pull/28948

**Comment by bucko13** [comment]
Dual funding channel protocol bolt merged

https://github.com/lightning/bolts/pull/851

**Comment by bucko13** [comment]
Cool transaction:
https://twitter.com/KeithMukai/status/1753178714441941392?cxt=HBwWoIa04ZCwxdQwAAAA&cn=ZmxleGlibGVfcmVjcw%3D%3D&refsrc=email

**Comment by bucko13** [comment]
Same word seeds:
https://twitter.com/raw_avocado/status/1753041127215604066?cxt=HBwWxIWxhcDnhtQwAAAA&cn=ZmxleGlibGVfcmVjcw%3D%3D&refsrc=email

**Comment by bucko13** [comment]
LNURL Challenges: 
https://stacker.news/items/400189

**Comment by bucko13** [comment]
semaphore p2p crowd funding on bitcoin: https://www.youtube.com/watch?v=VHGRQVuVtCY

**Comment by bucko13** [comment]
Taxonomy of fees in bitcoin smart contracts: https://delvingbitcoin.org/t/taxonomy-of-transaction-fees-in-smart-contracts/512

**Comment by bucko13** [comment]
Block stalling issue disclosure: https://delvingbitcoin.org/t/block-stalling-issue-in-core-prior-to-v22-0/499

**Comment by bucko13** [comment]
v3 anchors and 0conf: https://delvingbitcoin.org/t/0conf-ln-channels-and-v3-anchors/494

**Comment by bucko13** [comment]
[`sighash_outputdeltabounds`](https://delvingbitcoin.org/t/sighash-outputdeltabounds/504)

**Comment by bucko13** [comment]
v3 and some possible futures: https://delvingbitcoin.org/t/v3-and-some-possible-futures/523

**Comment by bucko13** [comment]
Citrea skepticism:
https://stacker.news/items/410156?commentId=410495
https://stacker.news/items/415012?commentId=415064

**Comment by bucko13** [comment]
Inscription marketplace running utxo arb on coinbase: https://twitter.com/mononautical/status/1758262223456162279?s=46&t=WMmqJ4MdyeBHjVDNEbJ-rg
