### ISSUE TITLE
March '24 Topics

### ISSUE THREAD

**Issue by bucko13** [austinbitdevs/austinbitdevs.com#31]

**Comment by bucko13** [comment]
Bitkey code open sourced: https://bitkey.build/sharing-the-code-behind-bitkey/

**Comment by justinmoon** [comment]
https://acinq.co/blog/phoenix-swaproot

**Comment by bucko13** [comment]
cap on sat denominated fees: https://x.com/MrHodl/status/1761755745580716287?s=20

**Comment by bucko13** [comment]
More tx acceleration services: https://twitter.com/renepickhardt/status/1760972080533651747

**Comment by bucko13** [comment]
Censorship to cover bitcoin core backdoors? https://stacker.news/items/440692

**Comment by bucko13** [comment]
OP_CAT vault

https://delvingbitcoin.org/t/basic-vault-prototype-using-op-cat/576

**Comment by bucko13** [comment]
Working Group lifecycle (and whether or not closed door development should be acceptable part of lifecycle): https://delvingbitcoin.org/t/workgroup-lifecycle/598

**Comment by bucko13** [comment]
Scalable & Permissionless Bitcoin CA
[delving bitcoin announcement](https://delvingbitcoin.org/t/scalable-permissionless-bitcoin-ca/596)
[Spaces Protocol](https://spacesprotocol.org/)

**Comment by bucko13** [comment]
[Liquidity provider utxo management](https://delvingbitcoin.org/t/liquidity-provider-utxo-management/600)

**Comment by bucko13** [comment]
[Proposal: OP_EXIT](https://delvingbitcoin.org/t/unilateral-exit/664)

**Comment by bucko13** [comment]
[GitLab Backups for Bitcoin Core repository](https://delvingbitcoin.org/t/gitlab-backups-for-bitcoin-core-repository/624)

**Comment by bucko13** [comment]
Price signaling for the future of the protocol: https://delvingbitcoin.org/t/economic-majority-signaling-for-op-ctv-activation/635

**Comment by bucko13** [comment]
[State minimization in MuSig2 signing sessions](https://delvingbitcoin.org/t/state-minimization-in-musig2-signing-sessions/626)

**Comment by bucko13** [comment]
Close to judgement in COPA v CSW case:
https://www.msn.com/en-us/money/technology/copa-vs-wright-what-s-at-stake-as-the-trial-to-determine-satoshi-s-identity-wraps-up/ar-BB1jJHN0

COPA Closing statement:
https://satoshi50.com/pdf/closing.pdf

**Comment by TonyGiorgio** [comment]
Marathon layer 2 https://ir.mara.com/news-events/press-releases/detail/1344/marathon-digital-holdings-introduces-anduro-a-new

**Comment by TonyGiorgio** [comment]
Mapping Human-Readable Names to Payment Instructions

https://groups.google.com/g/bitcoindev/c/uATaflkYglQ

**Comment by TonyGiorgio** [comment]
Revisiting BIP21

https://delvingbitcoin.org/t/revisiting-bip21/630

**Comment by TonyGiorgio** [comment]
Bitcoin Core 27.0 release candidate 1 available

https://groups.google.com/g/bitcoindev/c/jnK3CJAcbUE

**Comment by TonyGiorgio** [comment]
Unleashing Liquidity on the Lightning Network with “lightning-liquidity”

https://lightningdevkit.org/blog/unleashing-liquidity-on-the-lightning-network-with-lightning-liquidity/
