### ISSUE TITLE
April '24 Topics

### ISSUE THREAD

**Issue by bucko13** [austinbitdevs/austinbitdevs.com#32]

**Comment by bucko13** [comment]
Specter of MEV on Bitcoin: https://cyber.fund/content/the-spectre-of-mev-on-bitcoin

**Comment by justinmoon** [comment]
mercury layer lightning latch https://bitcoinmagazine.com/technical/mercury-layers-lightning-latch-swap-protocol

**Comment by justinmoon** [comment]
(last month we didn't get to `Liquidity Provider UTXO Management` or below)

**Comment by benthecarman** [comment]
https://github.com/lightningdevkit/rust-lightning/pull/2935

**Comment by benthecarman** [comment]
https://b10c.me/blog/012-viabtc-spv-vulnerability-disclosure/

**Comment by benthecarman** [comment]
https://github.com/lightningdevkit/rust-lightning/pull/2419

**Comment by benthecarman** [comment]
https://gofetch.fail/

**Comment by benthecarman** [comment]
https://stratumprotocol.org/blog/sri-1-0-0/

**Comment by justinmoon** [comment]
https://twitter.com/SamouraiWallet/status/1770560344865267954

**Comment by justinmoon** [comment]
https://twitter.com/PhoenixWallet/status/1771236080680841668

**Comment by justinmoon** [comment]
Laanwj's reaction to COPA verdict https://laanwj.github.io/2024/03/19/finally.html

**Comment by bucko13** [comment]
Permissionless bitvm verification bridge: https://bitvm.org/bitvm2

**Comment by bucko13** [comment]
Sigbash https://x.com/arbedout/status/1772646219317174680?s=20

**Comment by benthecarman** [comment]
https://github.com/supertestnet/hedgehog

**Comment by justinmoon** [comment]
https://x.com/arbedout/status/1772646219317174680?s=20

**Comment by justinmoon** [comment]
https://twitter.com/citrea_xyz/status/1770813889447432493

**Comment by benthecarman** [comment]
https://delvingbitcoin.org/t/great-consensus-cleanup-revival/710

**Comment by benthecarman** [comment]
https://b10c.me/blog/013-one-year-update-on-linkinglion/

**Comment by benthecarman** [comment]
https://gist.github.com/thesamesam/223949d5a074ebc3dce9ee78baad9e27

**Comment by bucko13** [comment]
Linux vulnerability https://x.com/niftynei/status/1774055520246137306?s=20

**Comment by bucko13** [comment]
Ledger without the ledger live

https://github.com/darosior/ledger_installer

**Comment by justinmoon** [comment]
bitkey review https://nunchuk.io/blog/bitkey

**Comment by benthecarman** [comment]
https://bluematt.bitcoin.ninja/2024/04/16/stop-calling-it-mev/

**Comment by benthecarman** [comment]
https://twitter.com/0xB10C/status/1780611768081121700

**Comment by TonyGiorgio** [comment]
https://twitter.com/roasbeef/status/1781086945986404559

**Comment by TonyGiorgio** [comment]
https://github.com/lightningnetwork/lnd/pull/8664
