### ISSUE TITLE
May 2024

### ISSUE THREAD

**Issue by justinmoon** [austinbitdevs/austinbitdevs.com#33]
https://x.com/robin_linus/status/1781832291938877704

**Comment by benthecarman** [comment]
https://www.justice.gov/usao-sdny/pr/founders-and-ceo-cryptocurrency-mixing-service-arrested-and-charged-money-laundering

**Comment by benthecarman** [comment]
https://stacker.news/items/524728/r/benthecarman

**Comment by bucko13** [comment]
Bitvmx white paper
https://bitvmx.org/

**Comment by benthecarman** [comment]
https://groups.google.com/g/bitcoindev/c/mR53go5gHIk

**Comment by benthecarman** [comment]
https://twitter.com/n1ckler/status/1787575188797681763

**Comment by justinmoon** [comment]
ark repo running on liquid https://github.com/ark-network/ark

**Comment by bucko13** [comment]
Wallet policy bip merged https://github.com/bitcoin/bips/pull/1389#event-12743501684

**Comment by benthecarman** [comment]
https://twitter.com/roasbeef/status/1788624974728790471

**Comment by benthecarman** [comment]
https://github.com/bitcoin/bitcoin/pull/28970

**Comment by benthecarman** [comment]
https://twitter.com/1440000bytes/status/1790245869700165684

**Comment by benthecarman** [comment]
https://delvingbitcoin.org/t/ecash-tides-using-cashu-and-stratum-v2/870

**Comment by benthecarman** [comment]
https://twitter.com/TheSingerLouis/status/1790824126472667227

**Comment by benthecarman** [comment]
https://blog.mutinywallet.com/blinded-authentication/
