### ISSUE TITLE
June 2024

### ISSUE THREAD

**Issue by benthecarman** [austinbitdevs/austinbitdevs.com#34]
We barely got to any topics last month, can pull some over as well

**Comment by bucko13** [comment]
DLCs with ecash notes 

https://conduition.io/cryptography/ecash-dlc/?ref=tftc.io

**Comment by benthecarman** [comment]
Ark open sourced

https://github.com/ark-network/

**Comment by benthecarman** [comment]
AI lightning routing

https://arxiv.org/pdf/2405.12087

**Comment by benthecarman** [comment]
https://eprint.iacr.org/2022/1676.pdf

**Comment by benthecarman** [comment]
https://brqgoo.medium.com/introducing-ark-v2-2e7ab378e87b

**Comment by bucko13** [comment]
[Great Consensus Cleanup Revival](https://delvingbitcoin.org/t/great-consensus-cleanup-revival/710)

the post is a little old, from back in March originally, but the convo has continued and it has some interesting and worthwhile discussion topics.

**Comment by benthecarman** [comment]
https://morehouse.github.io/lightning/lnd-onion-bomb/

**Comment by justinmoon** [comment]
https://x.com/robin_linus/status/1803118202764906970

**Comment by bucko13** [comment]
Mempool based fee estimation
https://delvingbitcoin.org/t/mempool-based-fee-estimation-on-bitcoin-core/703

**Comment by bucko13** [comment]
> https://x.com/robin_linus/status/1803118202764906970

otoh: https://bitcoin.stackexchange.com/questions/118928/what-does-it-mean-that-the-security-of-bitcoin-public-keys-and-256-bit-ecdsa-is#:~:text=From%20a%20security%20perspective%2C%20the,bits%2C%20which%20equals%2012%20words

**Comment by benthecarman** [comment]
https://threadreaderapp.com/thread/1800515195124748503.html
