### ISSUE TITLE
July 2024

### ISSUE THREAD

**Issue by benthecarman** [austinbitdevs/austinbitdevs.com#35]

**Comment by benthecarman** [comment]
https://brqgoo.medium.com/introducing-brollups-18ec4081f6e7 fucker drops it right after bitdevs

**Comment by benthecarman** [comment]
https://twitter.com/wikileaks/status/1805388007475732646

**Comment by benthecarman** [comment]
https://blog.qualys.com/vulnerabilities-threat-research/2024/07/01/regresshion-remote-unauthenticated-code-execution-vulnerability-in-openssh-server

**Comment by benthecarman** [comment]
https://github.com/bitcoin-core/bitcoincore.org/pull/1042

**Comment by benthecarman** [comment]
https://x.com/phoenixwallet/status/1808547081214439494?s=46

**Comment by benthecarman** [comment]
https://www.rfc-editor.org/rfc/rfc9591.html

**Comment by bucko13** [comment]
What's going on with hashrate: https://stacker.news/items/596736

**Comment by bucko13** [comment]
Weird bitcoin transaction analysis: https://stacker.news/items/593226

**Comment by benthecarman** [comment]
https://twitter.com/n1ckler/status/1810408548813213820

**Comment by bucko13** [comment]
Adding a link for an article of the security disclosures PR posted above 
https://bitcoincore.org/en/security-advisories/

**Comment by benthecarman** [comment]
https://delvingbitcoin.org/t/introduction-to-cluster-linearization/1032

**Comment by benthecarman** [comment]
https://twitter.com/PhoenixWallet/status/1811442125801705638

**Comment by bucko13** [comment]
Tor nodes down?
https://x.com/1440000bytes/status/1812469097864515950

**Comment by benthecarman** [comment]
https://twitter.com/StarkWareLtd/status/1813619696538939455

**Comment by bucko13** [comment]
"Mining pool game theory" or "Why isn't antpool mining ontop of its own blocks during splits" 
https://b10c.me/blog/014-mining-pool-game-theory-during-forks/
