### ISSUE TITLE
August 2024

### ISSUE THREAD

**Issue by bucko13** [austinbitdevs/austinbitdevs.com#36]

**Comment by bucko13** [comment]
Another super invention
https://x.com/super_testnet/status/1815792914812862609

**Comment by bucko13** [comment]
Verify SNARK with bitvmx
https://x.com/bitvmx/status/1816123923106259394

**Comment by bucko13** [comment]
FE'd up covenants https://rubin.io/public/pdfs/fedcov.pdf

**Comment by bucko13** [comment]
Dark Skippy attack: https://x.com/utxoclub/status/1820520960476561825

**Comment by niftynei** [comment]
https://x.com/jesseposner/status/1823769016764391521?s=46&t=WMmqJ4MdyeBHjVDNEbJ-rg

**Comment by benthecarman** [comment]
https://delvingbitcoin.org/t/stats-on-compact-block-reconstructions/1052

**Comment by sashafklein** [comment]
https://x.com/super_testnet/status/1820508871599014061 - Super testnet on Monero vs lightning for privacy
