### ISSUE TITLE
September 2024

### ISSUE THREAD

**Issue by bucko13** [austinbitdevs/austinbitdevs.com#37]

**Comment by bucko13** [comment]
Air gapped anti-exfil 
https://delvingbitcoin.org/t/non-interactive-anti-exfil-airgap-compatible/1081

**Comment by bucko13** [comment]
Opt in 0 conf with OP_CAT
https://x.com/matthewjablack/status/1826408792436687355

**Comment by benthecarman** [comment]
https://x.com/StarkWareLtd/status/1828059215283335547

**Comment by benthecarman** [comment]
https://groups.google.com/g/bitcoinminingdev/c/97fkfVmHWYU

**Comment by benthecarman** [comment]
https://petertodd.org/2024/covenant-dependent-layer-2-review

**Comment by benthecarman** [comment]
https://delvingbitcoin.org/t/superscalar-laddered-timeout-tree-structured-decker-wattenhofer-factories/1143

**Comment by benthecarman** [comment]
https://github.com/bitcoin/bitcoin/pull/28358

**Comment by benthecarman** [comment]
https://x.com/roasbeef/status/1835807639374274786
