### ISSUE TITLE
Nayuta wallet shutting down

### ISSUE THREAD

**Issue by TMan253** [austinbitdevs/austinbitdevs.com#44]
https://medium.com/nayuta-en/announcement-of-nayuta-inc-closure-d08b17c73dd8

He who panics first, panics best:  if you have sats with their LSP, evacuate them now.

**Comment by benthecarman** [comment]
@TMan253 thanks for all the topic suggestions!

if you could, it's easier for us if you put them all in the single monthly issue rather than making a new issue for each topic

**Comment by TMan253** [comment]
Will do, sir; and no sweat if some or all suggestions don’t make the final cut. :)On Sep 16, 2024, at 6:08 PM, benthecarman ***@***.***> wrote:﻿
@TMan253 thanks for all the topic suggestions!
if you could, it's easier for us if you put them all in the single monthly issue rather than making a new issue for each topic
