### ISSUE TITLE
October Topics

### ISSUE THREAD

**Issue by benthecarman** [austinbitdevs/austinbitdevs.com#45]

**Comment by bucko13** [comment]
Seedsigner "firmware" isn't what you think: https://gist.github.com/kdmukai/e270dd1c7b53b8daea4a9fc1ac89847c

**Comment by TMan253** [comment]
BOLT 12 merged into Lightning spec.
Announcement:  https://stacker.news/items/698612
Source:  https://github.com/lightning/bolts/blob/master/12-offer-encoding.md

**Comment by benthecarman** [comment]
https://ocean.xyz/docs/datum-setup

**Comment by benthecarman** [comment]
https://x.com/n1ckler/status/1843311745860849940

**Comment by benthecarman** [comment]
https://bitcoincore.org/en/2024/10/08/disclose-blocktxn-crash/

**Comment by benthecarman** [comment]
https://github.com/btcsuite/btcd/security/advisories/GHSA-27vh-h6mc-q6g8

**Comment by TMan253** [comment]
FYI, Coinbase added front-end taproot address support:  https://x.com/coinbaseassets/status/1843712761391399318?s=46&t=fmMSkrK7pqpQM0KQQmMMzg

**Comment by benthecarman** [comment]
https://2140.dev

**Comment by bucko13** [comment]
Bitcoin v28 rpc breaking changes: https://github.com/bitcoin/bitcoin/issues/31039

**Comment by bucko13** [comment]
Slow block propagation attack

**Comment by bucko13** [comment]
Wallet guide for new bitcoind rpc https://bitcoinops.org/en/bitcoin-core-28-wallet-integration-guide/

**Comment by bucko13** [comment]
Hybrid jamming mitigation https://delvingbitcoin.org/t/hybrid-jamming-mitigation-results-and-updates/1147

**Comment by bucko13** [comment]
Shielded client side validation

https://mailing-list.bitcoindevs.xyz/bitcoindev/b0afc5f2-4dcc-469d-b952-03eeac6e7d1b@gmail.com/

**Comment by bucko13** [comment]
DATUM links
https://bitcoinmagazine.com/technical/aaron-oceans-datum-is-tackling-bitcoins-most-pressing-problem

https://ocean.xyz/docs/datum

**Comment by bucko13** [comment]
Zero knowledge UTXO set inclusion proof
https://delvingbitcoin.org/t/proving-utxo-set-inclusion-in-zero-knowledge/1142

**Comment by TMan253** [comment]
Group channel opens for the LND+BOS plebs on Lightning Network+:

- What it is:  https://lightningnetwork.plus/posts/594
- How it works:  https://lightningnetwork.plus/posts/456

**Comment by TMan253** [comment]
Olaoluwa's LN Summit 2024 debrief from Japan:  https://delvingbitcoin.org/t/ln-summit-2024-notes-summary-commentary/1198
