### ISSUE TITLE
November Topics

### ISSUE THREAD

**Issue by benthecarman** [austinbitdevs/austinbitdevs.com#46]

**Comment by benthecarman** [comment]
https://lclhost.org/

**Comment by bucko13** [comment]
Free money?
https://x.com/sanket1729/status/1851824134680170792

**Comment by bucko13** [comment]
![elmo-hello](https://github.com/user-attachments/assets/b3defb62-9e42-4dc3-9bca-543dc63b3e92)

https://x.com/mononautical/status/1851830349208363379

**Comment by bucko13** [comment]
Censorship resistance in ecash mints?

https://github.com/bitcoinlayers/bitcoinlayers/pull/164#issuecomment-2453404755

**Comment by bucko13** [comment]
SuperScalar time tree channel factories

https://delvingbitcoin.org/t/superscalar-laddered-timeout-tree-structured-decker-wattenhofer-factories/1143

**Comment by kanzure** [comment]
https://github.com/bitcoinops/bitcoinops.github.io/pull/2018

**Comment by TMan253** [comment]
Sad day - Square winding down TBD, per SQ shareholder letter: 
https://s29.q4cdn.com/628966176/files/doc_financials/2024/q3/Shareholder_Letter_Block_3Q24.pdf
> We are ... winding down TBD. This gives us room to invest in our bitcoin mining initiative, which has strong product market fit and a healthy pipeline of demand, and Bitkey, our self-custody wallet for bitcoin.
Daniel Buckner indicates the Bitkey dex hackathon concluded, and dex and Web5 components were recently open-sourced if the community wants to continue development.  Web5 DWN and verifiable credentials work will continue as part of the Decentralized Identity Foundation (DIF):  https://x.com/csuwildcat/status/1855074773933461885

**Comment by benthecarman** [comment]
https://x.com/callebtc/status/1856679659523490046

**Comment by benthecarman** [comment]
https://x.com/moneyball/status/1854585339119341796

**Comment by benthecarman** [comment]
https://x.com/avihu28/status/1854570598439014807

**Comment by benthecarman** [comment]
https://x.com/n1ckler/status/1854552545084977320

**Comment by benthecarman** [comment]
https://x.com/jesseposner/status/1852394646997217742

**Comment by benthecarman** [comment]
https://x.com/bennyhodl/status/1853909096333754524
