### ISSUE TITLE
May topics

### ISSUE THREAD

**Issue by justinmoon** [austinbitdevs/austinbitdevs.com#5]
Post socratic topics!

**Comment by kanzure** [comment]
best of last 20 sessions

**Comment by benthecarman** [comment]
https://github.com/darosior/simple-anyprevout-vault

**Comment by justinmoon** [comment]
https://twitter.com/SomsenRuben/status/1519009818425671684?s=20&t=lyPz7ZUV9PBeoaLmFfYEPg

**Comment by benthecarman** [comment]
https://twitter.com/fiatjaf/status/1519296038766620672

**Comment by benthecarman** [comment]
https://twitter.com/bottlepay/status/1519745064267825152?t=QFkhlznGxHiNbpNO0QW2ag&s=19

**Comment by kanzure** [comment]
https://github.com/ElementsProject/secp256k1-zkp/issues/190

**Comment by kanzure** [comment]
https://www.blockchaincommons.com/quarterlies/Q1-2022/

**Comment by benthecarman** [comment]
https://github.com/lightningnetwork/lnd/pull/6361

**Comment by justinmoon** [comment]
Blockchain commons multisig scenario https://github.com/BlockchainCommons/SmartCustody/blob/master/Docs/Scenario-Multisig.md#appendices-further-information

**Comment by bucko13** [comment]
https://blog.ledger.com/miniscript-is-coming/

**Comment by benthecarman** [comment]
https://eprint.iacr.org/2022/510

**Comment by bucko13** [comment]
simple ctv spacechains: https://github.com/fiatjaf/simple-ctv-spacechain
https://twitter.com/fiatjaf/status/1519814017564483586

**Comment by cryptoquick** [comment]
https://rubin.io/bitcoin/2022/04/17/next-steps-bip119/

**Comment by justinmoon** [comment]
https://twitter.com/moneyball/status/1521852911046725632?s=20&t=eh-sOSMUhO86dI0OUZwIig

**Comment by bucko13** [comment]
Oldey but a goody, relevant to fork discussions and a topic from earlier in the year about syncing with old versions of core

https://github.com/bitcoin/bips/blob/master/bip-0050.mediawiki

**Comment by justinmoon** [comment]
https://twitter.com/carl_dong/status/1522240832522309633?s=20&t=OsMHTFOF8C-rKJbNG8NdOw

**Comment by supertestnet** [comment]
Two things I made this month:

- Bitcoin Chess: https://github.com/supertestnet/bitcoin-chess (uses key tweaking to hide chess moves in bitcoin pubkeys, meant to teach devs how key tweaking works)

- Vanilla JS browser wallet: https://github.com/supertestnet/vanilla-js-browser-wallet (a total of 642 lines of code including css and html, but not including the libraries I used, which are qrcode.js, bitcoin-js, noble-secp256k1, bip39, bip32, and buffer -- the purpose is so that web devs can easily customize it and put a non-custodial web wallet on their website or in their chrome extension)

**Comment by supertestnet** [comment]
This new lightning node in scala is also neat: https://github.com/fiatjaf/cliche

It is almost as bare bones of a lightning implementation as it is possible to get. It does not even require an external source of blockchain data because it has a built in electrum client for that. Fiatjaf is now using it as the backend for lntxbot and he positively raves about it.

**Comment by benthecarman** [comment]
https://blog.torproject.org/congestion-contrl-047/

**Comment by bucko13** [comment]
wallet policy proposal for better descriptor support in hardware wallets: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-May/020423.html

**Comment by ryanthegentry** [comment]
need to come up with a BEEF protocol using this so we can have ROAST-BEEF
https://twitter.com/real_or_random/status/1523964246945636352

**Comment by kanzure** [comment]
ROAST: https://twitter.com/real_or_random/status/1523964246945636352

https://eprint.iacr.org/2022/550

**Comment by justinmoon** [comment]
https://twitter.com/davidmarcus/status/1524826813096112128

**Comment by justinmoon** [comment]
https://twitter.com/jimmysong/status/1524778755947896838

**Comment by kanzure** [comment]
https://twitter.com/ChristopherA/status/1524934871637819392

**Comment by TonyGiorgio** [comment]
Analysis on blind signing with lightning https://lists.linuxfoundation.org/pipermail/lightning-dev/2022-May/003579.html

**Comment by bucko13** [comment]
Quantum protections: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-April/020209.html

**Comment by bucko13** [comment]
Oldest first coin selection in BDK: https://github.com/bitcoindevkit/bdk/pull/557

**Comment by justinmoon** [comment]
https://twitter.com/c_otto83/status/1525879972786749453?s=20&t=QB-WPRZSRB7N1-zmerOcMg

**Comment by benthecarman** [comment]
https://github.com/ElementsProject/lightning/releases/tag/v0.11.1

**Comment by benthecarman** [comment]
https://github.com/discreetlogcontracts/dlcspecs/pull/196

**Comment by supertestnet** [comment]
**Lightning Receiving Browser Wallet (non-custodial)**

https://github.com/supertestnet/lightning-receiving-browser-wallet

**Comment by justinmoon** [comment]
https://twitter.com/pwuille/status/1526680747901390854?s=20&t=xGRRTwSHI9zzL1y02MH4RA

**Comment by justinmoon** [comment]
https://aws.amazon.com/blogs/industries/experimenting-with-bitcoin-blockchain-on-aws/
