### ISSUE TITLE
June topics 

### ISSUE THREAD

**Issue by justinmoon** [austinbitdevs/austinbitdevs.com#7]
Post topic ideas for June!

**Comment by justinmoon** [comment]
https://twitter.com/cryptocecy/status/1527629299704025089

**Comment by justinmoon** [comment]
decentralized mixer
- demo: https://www.youtube.com/watch?app=desktop&v=Awcf-7G5vn8
- code: https://github.com/disnocen/dmix2

**Comment by supertestnet** [comment]
**Generating a cellular automata with Bitcoin Script**

[https://github.com/supertestnet/rule-110-in-bitcoin-script/blob/main/README.md](https://github.com/supertestnet/rule-110-in-bitcoin-script/blob/main/README.md)

**Comment by justinmoon** [comment]
Nice MEV + bitcoin thread https://twitter.com/roasbeef/status/1530256839954182144

**Comment by TonyGiorgio** [comment]
https://github.com/lightningdevkit/rust-lightning/pull/1401

**Comment by benthecarman** [comment]
https://github.com/bitcoin/bitcoin/pull/22702#issuecomment-1146017151

**Comment by bucko13** [comment]
AJ towns’ bitcoin banks
https://twitter.com/ajtowns/status/1534284646933880832?s=21&t=g8gDtWOqJqDTuVgQ8Xy7dQ

**Comment by bucko13** [comment]
Blog post on contributing to core: https://unchained.com/blog/contributing-bitcoin-core-patience/

**Comment by kanzure** [comment]
https://diyhpl.us/wiki/transcripts/btcpp/2022/fedimint-ecash/

**Comment by justinmoon** [comment]
https://gist.github.com/RubenSomsen/21c477c90c942acf45f8e8f5c1ad4fae

**Comment by kanzure** [comment]
https://twitter.com/roasbeef/status/1534366238507409408

**Comment by kanzure** [comment]
https://gist.github.com/AdamISZ/51349418be08be22aa2b4b469e3be92f

**Comment by kanzure** [comment]
1st silicon salon workshop completed https://www.siliconsalon.info/

**Comment by benthecarman** [comment]
https://github.com/bitcoin/bitcoin/pull/25353

**Comment by kanzure** [comment]
https://lightninglabs.substack.com/p/back-to-the-bitcoin-future-nows-the

**Comment by huumn** [comment]
More of an "announcement" than a topic, but Pavol asked me to help fill their sponsored seats at Bitcoin Commons: https://twitter.com/Trezor/status/1532026596470702083

**Comment by benthecarman** [comment]
https://gist.github.com/AdamISZ/51349418be08be22aa2b4b469e3be92f

**Comment by prusnak** [comment]
> More of an "announcement" than a topic, but Pavol asked me to help fill their sponsored seats at Bitcoin Commons: https://twitter.com/Trezor/status/1532026596470702083

Thanks Keyan for posting this! Although the original tweet mentions that end of open-call was 14th of June, we decided to extend the deadline until end of the week so people from the BitDevs meetup can also apply. We also added a shout-out to the event. https://twitter.com/trezor/status/1537100854486089728 I wish I was able to attend!

**Comment by bucko13** [comment]
bitcoin++ hackathon winner presentations:
lnuptime (voltage winners): https://www.lnuptime.com/
pLN by BitcoinDevShop (Samurai Winners): https://github.com/BitcoinDevShop/pln
Simpmint (Grand prize): @justinmoon got a link?

**Comment by justinmoon** [comment]
@bucko13 https://github.com/justinmoon/minimint/pull/5
