### ISSUE TITLE
August Topics

### ISSUE THREAD

**Issue by benthecarman** [austinbitdevs/austinbitdevs.com#9]

**Comment by benthecarman** [comment]
https://github.com/jamesob/mempool.work

**Comment by justinmoon** [comment]
https://twitter.com/EliBenSasson/status/1554046423234134016

**Comment by benthecarman** [comment]
https://github.com/bitcoin/bitcoin/pull/25766

**Comment by justinmoon** [comment]
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-July/020791.html

**Comment by benthecarman** [comment]
https://twitter.com/stephenlacy/status/1554697077430505473

**Comment by benthecarman** [comment]
https://arxiv.org/abs/2208.01908

**Comment by niftynei** [comment]
https://github.com/bitcoin/bitcoin/pull/23480

**Comment by benthecarman** [comment]
https://mailmanlists.org/pipermail/dlc-dev/2022-August/000149.html

**Comment by brilliancebitcoin** [comment]
**Interactive demo of blind schnorr sigs**
https://blindsigs.utxo.club/

**Comment by supertestnet** [comment]
**Interactive demo of blind schnorr sigs**
https://blindsigs.utxo.club/

**Comment by benthecarman** [comment]
https://twitter.com/base58btc/status/1559296871218176001

**Comment by benthecarman** [comment]
https://twitter.com/RTL_App/status/1558926546928250880

**Comment by kanzure** [comment]
Second Silicon Salon is scheduled for September 14, 2022 at 9am PT

https://www.siliconsalon.info/

**Comment by kanzure** [comment]
tornado cash, privacy and sanctions

**Comment by TonyGiorgio** [comment]
channel jamming https://lists.linuxfoundation.org/pipermail/lightning-dev/2022-August/003673.html

**Comment by supertestnet** [comment]
**Batching for Plebs (aka congestion control without a soft fork)**
https://telegra.ph/Batching-for-Plebs-aka-congestion-control-without-a-soft-fork-08-17
